CrudTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: CrudTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: statusAndcreatedAt
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName : createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
